### PR TITLE
Fix bad json serialization

### PR DESCRIPTION
**Pull request by artemio**

### CODE REVIEW

**Comment by mkdynamic** [comment]
Thanks for this PR @artemio, we can definitely merge this.

To better understand this, can you share some examples where the JSON would be invalid. Want to ensure the HTTP API is being a good citizen and always returning valid JSON.

**Comment by silentroach** [comment]
Got this sometimes:

    /www/masked/app.js:100
                throw e;
                ^

    SyntaxError: Unexpected end of JSON input
        at Object.parse (native)
        at Object.module.exports.load (/www/masked/node_modules/delighted/lib/serializer.js:21:23)
        at IncomingMessage.<anonymous> (/www/masked/node_modules/delighted/lib/Client.js:62:30)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:926:12)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by mkdynamic** [comment]
Thanks @silentroach -- would be interested to know what the raw JSON payload is in that case, and also the endpoint/method. Ideally the HTTP API should never return invalid JSON, so want to understand the source of that error better. Failing gracefully in the client is good nonetheless.

PR merged, thanks again @artemio. Will prepare a new release shortly and update here when it's available.

**Comment by mkdynamic** [comment]
Released in 1.1.3.

Thanks again folks.

**Pull request merged**
